deleted demo folder and moved the files

diff --git a/build/scripts/lakeshsahu22-ME_QA_XGOOGLE_FORM b/build/scripts/lakeshsahu22-ME_QA_XGOOGLE_FORM
--- a/build/scripts/lakeshsahu22-ME_QA_XGOOGLE_FORM
+++ b/build/scripts/lakeshsahu22-ME_QA_XGOOGLE_FORM
@@ -15,6 +15,8 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 #
+# SPDX-License-Identifier: Apache-2.0
+#
 
 ##############################################################################
 #
@@ -55,7 +57,7 @@
 #       Darwin, MinGW, and NonStop.
 #
 #   (3) This script is generated from the Groovy template
-#       https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
+#       https://github.com/gradle/gradle/blob/HEAD/platforms/jvm/plugins-application/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
 #       within the Gradle project.
 #
 #       You can find Gradle at https://github.com/gradle/gradle/.
@@ -80,13 +82,11 @@ do
     esac
 done
 
-APP_HOME=$( cd "${APP_HOME:-./}.." && pwd -P ) || exit
-
-APP_NAME="lakeshsahu22-ME_QA_XGOOGLE_FORM"
+# This is normally unused
+# shellcheck disable=SC2034
 APP_BASE_NAME=${0##*/}
-
-# Add default JVM options here. You can also use JAVA_OPTS and LAKESHSAHU22_ME_QA_XGOOGLE_FORM_OPTS to pass JVM options to this script.
-DEFAULT_JVM_OPTS=""
+# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
+APP_HOME=$( cd -P "${APP_HOME:-./}.." > /dev/null && printf '%s\n' "$PWD" ) || exit
 
 # Use the maximum available, or set MAX_FD != -1 to use that value.
 MAX_FD=maximum
@@ -114,7 +114,7 @@ case "$( uname )" in                #(
   NONSTOP* )        nonstop=true ;;
 esac
 
-CLASSPATH=$APP_HOME/lib/lakeshsahu22-ME_QA_XGOOGLE_FORM-1.0-SNAPSHOT.jar:$APP_HOME/lib/selenium-java-4.21.0.jar:$APP_HOME/lib/selenium-chrome-driver-4.21.0.jar:$APP_HOME/lib/selenium-devtools-v123-4.21.0.jar:$APP_HOME/lib/selenium-devtools-v124-4.21.0.jar:$APP_HOME/lib/selenium-devtools-v125-4.21.0.jar:$APP_HOME/lib/selenium-firefox-driver-4.21.0.jar:$APP_HOME/lib/selenium-devtools-v85-4.21.0.jar:$APP_HOME/lib/selenium-edge-driver-4.21.0.jar:$APP_HOME/lib/selenium-ie-driver-4.21.0.jar:$APP_HOME/lib/selenium-safari-driver-4.21.0.jar:$APP_HOME/lib/selenium-support-4.21.0.jar:$APP_HOME/lib/selenium-chromium-driver-4.21.0.jar:$APP_HOME/lib/selenium-remote-driver-4.21.0.jar:$APP_HOME/lib/selenium-manager-4.21.0.jar:$APP_HOME/lib/selenium-http-4.21.0.jar:$APP_HOME/lib/selenium-json-4.21.0.jar:$APP_HOME/lib/selenium-os-4.21.0.jar:$APP_HOME/lib/selenium-api-4.21.0.jar:$APP_HOME/lib/auto-service-annotations-1.1.1.jar:$APP_HOME/lib/guava-33.2.0-jre.jar:$APP_HOME/lib/opentelemetry-semconv-1.25.0-alpha.jar:$APP_HOME/lib/opentelemetry-exporter-logging-1.38.0.jar:$APP_HOME/lib/opentelemetry-sdk-extension-autoconfigure-1.38.0.jar:$APP_HOME/lib/opentelemetry-sdk-extension-autoconfigure-spi-1.38.0.jar:$APP_HOME/lib/opentelemetry-sdk-1.38.0.jar:$APP_HOME/lib/opentelemetry-sdk-trace-1.38.0.jar:$APP_HOME/lib/opentelemetry-sdk-metrics-1.38.0.jar:$APP_HOME/lib/opentelemetry-sdk-logs-1.38.0.jar:$APP_HOME/lib/opentelemetry-sdk-common-1.38.0.jar:$APP_HOME/lib/opentelemetry-api-incubator-1.38.0-alpha.jar:$APP_HOME/lib/opentelemetry-api-1.38.0.jar:$APP_HOME/lib/opentelemetry-context-1.38.0.jar:$APP_HOME/lib/byte-buddy-1.14.15.jar:$APP_HOME/lib/failsafe-3.3.2.jar:$APP_HOME/lib/failureaccess-1.0.2.jar:$APP_HOME/lib/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:$APP_HOME/lib/jsr305-3.0.2.jar:$APP_HOME/lib/checker-qual-3.42.0.jar:$APP_HOME/lib/error_prone_annotations-2.26.1.jar:$APP_HOME/lib/commons-exec-1.4.0.jar
+CLASSPATH=$APP_HOME/lib/lakeshsahu22-ME_QA_XGOOGLE_FORM.jar:$APP_HOME/lib/testng-7.11.0.jar:$APP_HOME/lib/selenium-java-4.29.0.jar:$APP_HOME/lib/slf4j-api-2.0.16.jar:$APP_HOME/lib/jcommander-1.83.jar:$APP_HOME/lib/jquery-3.7.1.jar:$APP_HOME/lib/selenium-chrome-driver-4.29.0.jar:$APP_HOME/lib/selenium-devtools-v131-4.29.0.jar:$APP_HOME/lib/selenium-devtools-v132-4.29.0.jar:$APP_HOME/lib/selenium-devtools-v133-4.29.0.jar:$APP_HOME/lib/selenium-devtools-v85-4.29.0.jar:$APP_HOME/lib/selenium-edge-driver-4.29.0.jar:$APP_HOME/lib/selenium-firefox-driver-4.29.0.jar:$APP_HOME/lib/selenium-ie-driver-4.29.0.jar:$APP_HOME/lib/selenium-safari-driver-4.29.0.jar:$APP_HOME/lib/selenium-support-4.29.0.jar:$APP_HOME/lib/selenium-chromium-driver-4.29.0.jar:$APP_HOME/lib/selenium-remote-driver-4.29.0.jar:$APP_HOME/lib/selenium-manager-4.29.0.jar:$APP_HOME/lib/selenium-http-4.29.0.jar:$APP_HOME/lib/selenium-json-4.29.0.jar:$APP_HOME/lib/selenium-os-4.29.0.jar:$APP_HOME/lib/selenium-api-4.29.0.jar:$APP_HOME/lib/jspecify-1.0.0.jar:$APP_HOME/lib/auto-service-annotations-1.1.1.jar:$APP_HOME/lib/guava-33.4.0-jre.jar:$APP_HOME/lib/opentelemetry-semconv-1.28.0-alpha.jar:$APP_HOME/lib/opentelemetry-exporter-logging-1.46.0.jar:$APP_HOME/lib/opentelemetry-sdk-extension-autoconfigure-1.46.0.jar:$APP_HOME/lib/opentelemetry-sdk-extension-autoconfigure-spi-1.46.0.jar:$APP_HOME/lib/opentelemetry-sdk-1.46.0.jar:$APP_HOME/lib/opentelemetry-sdk-trace-1.46.0.jar:$APP_HOME/lib/opentelemetry-sdk-metrics-1.46.0.jar:$APP_HOME/lib/opentelemetry-sdk-logs-1.46.0.jar:$APP_HOME/lib/opentelemetry-sdk-common-1.46.0.jar:$APP_HOME/lib/opentelemetry-api-incubator-1.46.0-alpha.jar:$APP_HOME/lib/opentelemetry-api-1.46.0.jar:$APP_HOME/lib/opentelemetry-context-1.46.0.jar:$APP_HOME/lib/byte-buddy-1.15.11.jar:$APP_HOME/lib/failureaccess-1.0.2.jar:$APP_HOME/lib/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:$APP_HOME/lib/jsr305-3.0.2.jar:$APP_HOME/lib/checker-qual-3.43.0.jar:$APP_HOME/lib/error_prone_annotations-2.36.0.jar:$APP_HOME/lib/j2objc-annotations-3.0.0.jar:$APP_HOME/lib/commons-exec-1.4.0.jar
 
 
 # Determine the Java command to use to start the JVM.
@@ -133,22 +133,29 @@ location of your Java installation."
     fi
 else
     JAVACMD=java
-    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
+    if ! command -v java >/dev/null 2>&1
+    then
+        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
 
 Please set the JAVA_HOME variable in your environment to match the
 location of your Java installation."
+    fi
 fi
 
 # Increase the maximum file descriptors if we can.
 if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
     case $MAX_FD in #(
       max*)
+        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
+        # shellcheck disable=SC2039,SC3045
         MAX_FD=$( ulimit -H -n ) ||
             warn "Could not query maximum file descriptor limit"
     esac
     case $MAX_FD in  #(
       '' | soft) :;; #(
       *)
+        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
+        # shellcheck disable=SC2039,SC3045
         ulimit -n "$MAX_FD" ||
             warn "Could not set maximum file descriptor limit to $MAX_FD"
     esac
@@ -193,15 +200,19 @@ if "$cygwin" || "$msys" ; then
     done
 fi
 
-# Collect all arguments for the java command;
-#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $LAKESHSAHU22_ME_QA_XGOOGLE_FORM_OPTS can contain fragments of
-#     shell script including quotes and variable substitutions, so put them in
-#     double quotes to make sure that they get re-expanded; and
-#   * put everything else in single quotes, so that it's not re-expanded.
+
+# Add default JVM options here. You can also use JAVA_OPTS and LAKESHSAHU22_ME_QA_XGOOGLE_FORM_OPTS to pass JVM options to this script.
+DEFAULT_JVM_OPTS=""
+
+# Collect all arguments for the java command:
+#   * DEFAULT_JVM_OPTS, JAVA_OPTS, JAVA_OPTS, and optsEnvironmentVar are not allowed to contain shell fragments,
+#     and any embedded shellness will be escaped.
+#   * For example: A user cannot expect ${Hostname} to be expanded, as it is an environment variable and will be
+#     treated as '${Hostname}' itself on the command line.
 
 set -- \
         -classpath "$CLASSPATH" \
-        demo.App \
+        App \
         "$@"
 
 # Stop when "xargs" is not available.
